
package net.xqx.service.certificate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CertificateRegServiceImplService", targetNamespace = "http://certificate.service.xqx.net/", wsdlLocation = "http://localhost:8090/ExamRegService/services/certificate?wsdl")
public class CertificateRegServiceImplService
    extends Service
{

    private final static URL CERTIFICATEREGSERVICEIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/ExamRegService/services/certificate?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CERTIFICATEREGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public CertificateRegServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CertificateRegServiceImplService() {
        super(CERTIFICATEREGSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://certificate.service.xqx.net/", "CertificateRegServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns CertificateRegService
     */
    @WebEndpoint(name = "CertificateRegServiceImplPort")
    public CertificateRegService getCertificateRegServiceImplPort() {
        return (CertificateRegService)super.getPort(new QName("http://certificate.service.xqx.net/", "CertificateRegServiceImplPort"), CertificateRegService.class);
    }

}
