
package net.xqx.service.certificate;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CertificateRegService", targetNamespace = "http://certificate.service.xqx.net/")
public interface CertificateRegService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.xqx.service.certificate.CertificateReg>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCertificates", targetNamespace = "http://certificate.service.xqx.net/", className = "net.xqx.service.certificate.GetCertificates")
    @ResponseWrapper(localName = "getCertificatesResponse", targetNamespace = "http://certificate.service.xqx.net/", className = "net.xqx.service.certificate.GetCertificatesResponse")
    public List<CertificateReg> getCertificates(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
