
package net.xqx.service.achievement;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AchievementService", targetNamespace = "http://achievement.service.xqx.net/")
public interface AchievementService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<net.xqx.service.achievement.Achievement>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAchievements", targetNamespace = "http://achievement.service.xqx.net/", className = "net.xqx.service.achievement.GetAchievements")
    @ResponseWrapper(localName = "getAchievementsResponse", targetNamespace = "http://achievement.service.xqx.net/", className = "net.xqx.service.achievement.GetAchievementsResponse")
    public List<Achievement> getAchievements(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
